# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run all the tests in the world!"
  lane :unitTestLane do
    scan(
      devices: ["iPhone 14"],
      scheme: "test_fastlane_reports",
      ensure_devices_found: true,
      open_report: true
    )
  end
end
