name: PullRequest

on:
  pull_request:
    branches: [ "main" ]

jobs:
  unitTests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: bundle exec fastlane installDependencies
    - name: Run Unit Tests
      run: bundle exec fastlane unitTestLane
